#!/bin/bash

# Script to pops a notification when the switching the workspace for XFCE 
#
# * Gesture switching using libinput
# 1. add this file to /usr/local/bin/harry-libinput-workspace-switcher
# 2. edit: ~/.config/libinput-gestures.conf
#   # Move between workspaces wrapped - left and right flipped for natural scrolling 
#   gesture swipe right 3 harry-libinput-workspace-switcher left 
#   gesture swipe left  3 harry-libinput-workspace-switcher right 
# 
# * Keyboard switching with the hotkeys 
# 1. Go to Window Manager and disable the hot key switch 
# 2. To to Keyboard and set up shortcuts 
#
#
# Alternative polling solution: 
# https://forum.xfce.org/viewtopic.php?id=9200


# Workspace number starts at 0 as all things should 
TITLE="Workspace"
WORKSPACE_NUM=$(wmctrl -d | wc -l)
WORKSPACE_CURRENT=$(wmctrl -d | grep \* | cut -d' ' -f1)

if [ $1 = "left" ]; then
    WORKSPACE_TARGET=$(($WORKSPACE_CURRENT-1))
    if [ $WORKSPACE_TARGET -lt 0 ]; then
        WORKSPACE_TARGET=$(($WORKSPACE_NUM-1)) 
    fi
    wmctrl -s $WORKSPACE_TARGET
    notify-send $TITLE $WORKSPACE_TARGET 
elif [ $1 = "right" ]; then 
    WORKSPACE_TARGET=$(($WORKSPACE_CURRENT+1))
    if [ $WORKSPACE_TARGET -ge $WORKSPACE_NUM ]; then
        WORKSPACE_TARGET=0 
    fi
    wmctrl -s $WORKSPACE_TARGET
    notify-send $TITLE $WORKSPACE_TARGET 
else
    notify-send $TITLE "specify left or right to this command" 
fi

